settings:
  title: 'Plex (and Adjacent) Services Status Page'
  url: 'https://check.izzo.one/' # used for Slack messages
  logo: plex-logo.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: plex-izzo-one-bazarr # unique identifier
    name: Bazarr
    description: 'Subtitle Downloader' # default=empty
    url: 'https://plex.izzo.one/bazarr' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: plex-izzo-one-lidarr
    name: Lidarr
    description: 'Music Downloader'
    url: 'https://plex.izzo.one/lidarr'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false    
    linkable: true # allows the title to be a link, default=true

  - id: overseerr-izzo-one
    name: Overseerr
    description: 'Request Service for Plex'
    url: 'https://overseerr.izzo.one/'
    method: GET
    followRedirect: true # should fetch follow redirects, default=false    
    linkable: true # allows the title to be a link, default=true
    expectStatus: 200

  - id: plex-izzo-one-prowlarr
    name: Prowlarr
    description: 'Indexer Manager'
    url: 'https://plex.izzo.one/prowlarr'
    method: GET
    followRedirect: true # should fetch follow redirects, default=false    
    linkable: true # allows the title to be a link, default=true
    expectStatus: 200

  - id: plex-izzo-one-radarr
    name: Radarr
    description: 'Movie Downloader'
    url: 'https://plex.izzo.one/radarr'
    method: GET
    followRedirect: true # should fetch follow redirects, default=false    
    linkable: true # allows the title to be a link, default=true
    expectStatus: 200    

  - id: plex-izzo-one-sabnzbd
    name: Sabnzbd
    description: 'NZB Downloader'
    url: 'https://plex.izzo.one/sabnzbd'
    method: GET
    followRedirect: true # should fetch follow redirects, default=false    
    linkable: true # allows the title to be a link, default=true
    expectStatus: 200    

  - id: plex-izzo-one-sonarr
    name: Overseerr
    description: 'TV Show Downloader'
    url: 'https://plex.izzo.one/sonarr'
    method: GET
    followRedirect: true # should fetch follow redirects, default=false    
    linkable: true # allows the title to be a link, default=true
    expectStatus: 200

  - id: plex-izzo-one-qb
    name: qBittorrent
    description: 'Torrent Downloader'
    url: 'https://plex.izzo.one/qb'
    method: GET
    followRedirect: true # should fetch follow redirects, default=false    
    linkable: true # allows the title to be a link, default=true
    expectStatus: 200    
